name: Build and run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install packages
      run: sudo apt install -y gcc-mingw-w64-x86-64 make xorg-dev
      
    - name: Build for all platforms
      run: make all
      
    - name: Test linux
      run: make test-linux
      
